//Number Guessing Game 
import java.util.Scanner;
class Game
{
    public static void main(String[] args)
    {
        Scanner s = new Scanner(System.in);

        int numOfChances = 10;

        //Generating a Random Number using Math.random function

        // Math.random generates a number between 0.0 and 1.0, so to increase its value we multiply it with some multiplicity factor.

        int target = (int)(10*Math.random()) + (1000* (int)(Math.random()));

        for (int i =1; i<=numOfChances; i++)
        {
            System.out.println("Please enter your number : ");

            // Taking the input from the user
            int guessedNum = s.nextInt();

            
            // Writing the Logical condition if guessed number is less than the Target number generated by the computer.
            if (guessedNum < target)
            {
                System.out.println("Your Number is LESS than the Correct answer");
                if (i<numOfChances)
                {
                    System.out.println("Now you have only " + (numOfChances-i) + " chances left");
                    System.out.println("-------------------------------------------------------------------");
                }

                else
                {
                    System.out.println("GAME OVER!");
                    System.out.println("Your number of trials ended");
                    System.out.println("The correct answer was "+target);

                }                         
                
            }

            // Writing the logical condition if guessed number is greater than the Target number.
            else if (guessedNum > target)
            {
                System.out.println("Your Number is GREATER than the Correct answer");
                if (i<numOfChances)
                {
                    System.out.println("Now you have only " + (numOfChances-i) + " chances left" );
                    System.out.println("---------------------------------------------------------------------");
                }

                else
                {
                    System.out.println("GAME OVER!");
                    System.out.println("Your number of trials ended");
                    System.out.println("The correct answer was "+target);
                }                         
                
            }

            // Writing the logical condition if the guessed number is equal to the Target number.
            else{

                System.out.println("CONGRATULATIONS!!!!!");
                System.out.println("You have guessed the Correct Number");
                break;
            }
        }

    }
}